spring.profiles.active=dev

spring.application.name=fic_attendance_tracker

server.tomcat.accesslog.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql://dpg-d78v3hk50q8c73f7nvr0-a.oregon-postgres.render.com/fic_attendance_tracker_db_gpa0
spring.datasource.username=fic_attendance_tracker_db_user
spring.datasource.password=mLBQ7jn2Ea9RD5uJO0FrHiEXU5NK3RDU

# spring.datasource.url=jdbc:postgresql://dpg-d6kuf0l6ubrc73epn1ng-a/fic_attendance_tracker_db
# spring.datasource.username=${DB_USER}
# spring.datasource.password=${DB_PASS}

spring.session.jdbc.initialize-schema=always