spring.profiles.active=dev

spring.application.name=fic_attendance_tracker

server.tomcat.accesslog.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql://dpg-d6kuf0l6ubrc73epn1ng-a.oregon-postgres.render.com/fic_attendance_tracker_db
spring.datasource.username=fic_attendance_tracker_db_user
spring.datasource.password=YntSEPWCW5MIrDprwtUvh8cWWO2toc2A

# spring.datasource.url=jdbc:postgresql://dpg-d6kuf0l6ubrc73epn1ng-a/fic_attendance_tracker_db
# spring.datasource.username=${DB_USER}
# spring.datasource.password=${DB_PASS}

spring.session.jdbc.initialize-schema=always